semantic_waypoints:
  frame_id: odom

  points:
    home:
      x: 0.0
      y: 0.0
      yaw: 0.0

    search_area:
      x: 1.5
      y: 0.0
      yaw: 0.0

    red_bin:
      x: 2.5
      y: 1.0
      yaw: 1.57

    green_bin:
      x: 2.5
      y: 0.0
      yaw: 1.57

    blue_bin:
      x: 2.5
      y: -1.0
      yaw: 1.57

    gray_bin:
      x: 2.5
      y: -1.5
      yaw: 1.57

    staging_area:
      x: 1.0
      y: 0.0
      yaw: 0.0

    safe_stop_area:
      x: 0.0
      y: -1.0
      yaw: 0.0